### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by mebert1** [LoyolaChicagoCode/consoleapp-java#6]
### Problem:
Current code throws "IllegalArgumentException" when executed in Windows 10 environment.

### Cause:
Windows returns String "Windows 10" when function System.getProperty("os.name") is called.
If statement at hw.Main.main (Main.java:60) will return TRUE and therefore execute code in line 61.
Line 61 is not compatible with Windows environment.

### Solution idea:
Make program executable on multiple operating systems:
Use "string".split(" ") function on returned String of getProperty function. Then only compare first array entry to String "Windows".
`if (!"Windows".equals(System.getProperty("os.name").split(" ")[0])) {`

**Comment by klaeufer** [comment]
Valid point! Fixed with df502b5.
